sonar.projectKey=krrishitejas_ZeroGate-Red-Teaming
sonar.organization=krrishitejas
sonar.projectName=ZeroGate-Red-Teaming

sonar.sources=zerogate_red_teaming
sonar.tests=zerogate_red_teaming/tests
sonar.exclusions=**/__pycache__/**,**/*.pyc,zerogate_red_teaming/tests/**
sonar.security.exclusions=zerogate_red_teaming/tests/**

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
